function paretoguide

fig = figure( ...
    'Name','paretoguide', ...
    'NumberTitle','off', ...
    'MenuBar','none', ...
    'ToolBar','none', ...
    'Resize','off', ...
    'Color',[1.000 0.800 0.930], ...
    'Position',[680 80 560 650]);

btnColor = [0.494 0.184 0.557];

uicontrol(fig,'Style','text', ...
    'String','Paretoscript', ...
    'Units','normalized', ...
    'Position',[0.02 0.92 0.35 0.06], ...
    'BackgroundColor',[1.000 0.800 0.930], ...
    'ForegroundColor',[0 0.45 0.85], ...
    'FontSize',20, ...
    'FontWeight','bold', ...
    'HorizontalAlignment','left');

uicontrol(fig,'Style','text', ...
    'String',sprintf('this program will draw pareto diagram for water\npollutions and draw The fishbone diagram (cause\nand effect) for the pollutions'), ...
    'Units','normalized', ...
    'Position',[0.08 0.80 0.84 0.11], ...
    'BackgroundColor',[0.94 0.94 0.94], ...
    'ForegroundColor',[0 0.45 0.85], ...
    'FontSize',13, ...
    'FontWeight','bold');

makeBtn('plotting water parameters',[0.05 0.70 0.42 0.07],@(~,~) evalin('base','plotting'));
makeBtn('pareto table',[0.53 0.70 0.42 0.07],@(~,~) evalin('base','paretotable'));
makeBtn('pareto diagram',[0.05 0.61 0.42 0.07],@(~,~) evalin('base','paretoplot'));
makeBtn('simulated pareto diagram',[0.53 0.61 0.42 0.07],@(~,~) evalin('base','simparetoplot'));
makeBtn('comparision between the diagrams',[0.18 0.50 0.64 0.07],@(~,~) evalin('base','compairing'));

uicontrol(fig,'Style','text', ...
    'String','chose the priority to plot cause and effect diagram', ...
    'Units','normalized', ...
    'Position',[0.08 0.405 0.84 0.04], ...
    'BackgroundColor',btnColor, ...
    'ForegroundColor',[1 1 1], ...
    'FontSize',12, ...
    'FontWeight','bold');

uicontrol(fig,'Style','popupmenu', ...
    'String',{'Select priority','First Priority','Second Priority','Third Priority','Fourth Priority'}, ...
    'Units','normalized', ...
    'Position',[0.08 0.36 0.84 0.045], ...
    'BackgroundColor','white', ...
    'ForegroundColor',[0 0 0], ...
    'FontSize',11, ...
    'Callback',@priorityCallback);

makeBtn('Water Quality Index (WQI)',[0.22 0.27 0.56 0.065],@(~,~) evalin('base','plot_wqi'));
makeBtn('AI Analysis (Random Forest)',[0.18 0.18 0.64 0.065],@(~,~) evalin('base','ai_random_forest'),[0.13 0.60 0.40]);
makeBtn('Help',[0.34 0.09 0.32 0.065],@(~,~) openHelp);
makeBtn('Close',[0.34 0.01 0.32 0.065],@(~,~) close(fig));

    function makeBtn(txt,pos,callback,color)
        if nargin < 4
            color = btnColor;
        end
        uicontrol(fig,'Style','pushbutton', ...
            'String',txt, ...
            'Units','normalized', ...
            'Position',pos, ...
            'BackgroundColor',color, ...
            'ForegroundColor',[1 1 1], ...
            'FontSize',11, ...
            'FontWeight','bold', ...
            'Callback',callback);
    end

    function priorityCallback(src,~)
        val = get(src,'Value');
        switch val
            case 2
                evalin('base','firstpriority');
            case 3
                evalin('base','secondpriority');
            case 4
                evalin('base','thirdpriority');
            case 5
                evalin('base','forthpriority');
        end
    end

    function openHelp
        try
            winopen('help.txt');
        catch
            edit('help.txt');
        end
    end

end